[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ibuidl_social = "5U1JcXgwu8D7S2sWN15fDwfEC4fXqM2wn6gHNgba9HXi"

[programs.devnet]
ibuidl_social = "5U1JcXgwu8D7S2sWN15fDwfEC4fXqM2wn6gHNgba9HXi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
api = "yarn run ts-node app/index.ts"

# 在用localhost测试时，把其他测试地址的token_metadata_program复制到本地网络执行
# [test.validator]
# bind_address = "0.0.0.0"
# url = "https://mainnet.helius-rpc.com/?api-key=fb252456-993c-4a77-9a32-3c7456029875"
# ledger = "./anchor/test-ledger"
# rpc_port = 8899

# [[test.validator.clone]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
